version: '1.5.5'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    restart: always
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/logs
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+8:00
      - --lower-case-table-names=1

  redis:
    container_name: redis
    image: redis:7.0.11
    ports:
      - "6379:6379"
    restart: always
    build:
      context: ./docker/redis
    volumes:
      - ./docker/redis/conf/redis.conf:/opt/redis/redis.conf
      - ./docker/redis/data:/data
      - ./docker/redis/logs:/logs
    environment:
        - REDIS_PASSWORD=password
    command:
      redis-server /opt/redis/redis.conf
