# Spring 配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tang-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: password
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: password

# 接口文档配置
springdoc:
  swagger-ui:
    # 是否开启
    enabled: true
    # 访问路径
    path: /api-docs

# 日志配置
logging:
  # 日志级别
  level:
    org:
      springframework: warn
    com:
      tang: debug
