# 项目配置
tang:
  # 名称
  name: 糖猫猫后台管理系统
  # 版本
  version: 1.5.3

# 环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat 最大线程数，默认为200
      max: 800
      # tomcat 启动初始化的线程数，默认值10
      min-spare: 100

# Spring 配置
spring:
  # 运行环境
  profiles:
    active: @profileActive@
  # Jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# MyBatis 配置
mybatis:
    # 搜索指定包别名
    # typeAliasesPackage: com.tang.**.entity
    # 配置 mapper 的扫描，找到所有的 mapper.xml 映射文件
    mapper-locations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    # configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  # 日志格式
  pattern:
    dateformat: HH:mm:ss.SSS

# token 配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥 Create by https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx 256-bit with Hex
  secret: 556A586E3272357538782F413F4428472D4B6150645367566B59703373367639
  # 时间颗粒度
  time-unit: hours
  # 令牌有效期
  expire-time: 2
