# 项目配置
tang:
  # 演示模式
  demo-mode: true

# 文件配置
file:
  # 文件上传路径
  uploads: /root/uploads/tang-boot

# Spring 配置
spring:
  # 数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tang-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: password
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: password

# 第三方登录
oauth:
  github:
    # 客户端ID
    client-id: Iv1.2f8ee47264aa7c54
    # 客户端密钥
    client-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # 回调地址
    redirect-url: http://116.196.102.213/redirect
