name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Modify configuration files
      run: |
        sed -i 's#<property name="LOG_PATH" value=".*" />#<property name="LOG_PATH" value="${{ secrets.LOG_PATH }}" />#' tang-admin/src/main/resources/logback.xml
        sed -i '0,/password: .*/s/password: .*/password: ${{ secrets.DATABASE_PASSWORD }}/' tang-admin/src/main/resources/application-prod.yml
        sed -i '/password: .*/{n;s/password: .*/password: ${{ secrets.REDIS_PASSWORD }}/}' tang-admin/src/main/resources/application-prod.yml
        echo -e 'tang:\n  uploads: ${{ secrets.UPLOAD_PATH }}' >> tang-admin/src/main/resources/application-prod.yml
        cat tang-admin/src/main/resources/logback.xml
        cat tang-admin/src/main/resources/application-prod.yml

    - name: Build with Maven
      run: sh bin/package.sh
